@startuml
top to bottom direction
skinparam linetype ortho
skinparam classAttributeIconSize 0
hide empty members

abstract class ProgramGenerator {
    +run() : QString
}

class Generator {
    -params : Params
    +run() : QString
}

abstract class ProgramDecorator {
    -generator : ProgramGenerator
    +run() : QString
}

class SafetyLineDecorator {
    +run() : QString
}

class WorkpieceDecorator {
    +run() : QString
}

ProgramGenerator <|-- Generator
ProgramGenerator <|-- ProgramDecorator

ProgramDecorator *--> ProgramGenerator

ProgramDecorator <|-- SafetyLineDecorator
ProgramDecorator <|-- WorkpieceDecorator

ProgramGenerator -[hidden]down- Generator
ProgramGenerator -[hidden]down- ProgramDecorator
ProgramDecorator -[hidden]down- SafetyLineDecorator
ProgramDecorator -[hidden]down- WorkpieceDecorator
@enduml