@startuml
top to bottom direction
skinparam linetype ortho
skinparam classAttributeIconSize 0
skinparam nodesep 50
skinparam ranksep 60
hide empty members

interface OperationModule {
    +getControlWidget(): QWidget
    +getPreviewWidget(): QWidget
}

class App {
    -ControlWidget: QWidget
    -PreviewWidget: PreviewWidget
}

class PocketModule {
    -controlWidget : QWidget
    -previewWidget : PreviewWidget
    +getControlWidget(): QWidget
    +getPreviewWidget(): QWidget
}

class DrillingModule {
    -controlWidget : QWidget
    -previewWidget : PreviewWidget
    +getControlWidget(): QWidget
    +getPreviewWidget(): QWidget
}

abstract class QWidget {
}

class PreviewWidget {
    +previewEdit: QPlainTextEdit
    +update()
}

class PocketControlWidget {
}

class DrillingControlWidget {
}

OperationModule <|-- PocketModule
OperationModule <|-- DrillingModule
App ..> OperationModule

QWidget <|-- PocketControlWidget
QWidget <|-- DrillingControlWidget
QWidget <|-- PreviewWidget

App ..> QWidget
App ..> PreviewWidget

PocketModule --> PocketControlWidget
PocketModule --> PreviewWidget
DrillingModule --> DrillingControlWidget
DrillingModule --> PreviewWidget

App -[hidden]down-> OperationModule
OperationModule -[hidden]down-> PocketModule
PocketModule -[hidden]right-> DrillingModule

OperationModule -[hidden]down-> QWidget
QWidget -[hidden]down-> PreviewWidget
PreviewWidget -[hidden]down-> PocketControlWidget
PocketControlWidget -[hidden]right-> DrillingControlWidget

@enduml